name: Deploy
on:
  push:
    branches:
      - production
  workflow_dispatch:
      
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.13.x'
      - run: |
        docker compose down
        docker compose build app
        docker compose up -d
