name: Deploy
on:
  push:
    branches:
      - production
  workflow_dispatch:
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.13.x'
      - run: npm install
      - run: npm test
